source("Functions.R")
tree <- ape::read.tree("camp.fossils.rootcon.dated.2.tre")
print(tree)
data <- read.delim("camp.trop.temp.txt", stringsAsFactors = FALSE)
head(data)
rownames(data) <- data[,1]
pruned <- geiger::treedata(tree, data, warnings=TRUE)
tree <- pruned$phy
data <- pruned$data
data <- data.frame(species=data[,"species"], region=as.numeric(data[,"region"]), tot.records=as.numeric(data[,"tot.records"]), stringsAsFactors=FALSE)
head(data)
print(tree)
result1_0.5 <- DoSingleAnalysis(tree, data, 0.5, n.cores=2, rate.cat=1, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.5.rda")
result2_0.5 <- DoSingleAnalysis(tree, data, 0.5, n.cores=2, rate.cat=2, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.5.rda")
result3_0.5 <- DoSingleAnalysis(tree, data, 0.5, n.cores=2, rate.cat=3, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.5.rda")
result4_0.5 <- DoSingleAnalysis(tree, data, 0.5, n.cores=2, rate.cat=4, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.5.rda")
result1_0.1 <- DoSingleAnalysis(tree, data, 0.1, n.cores=2, rate.cat=1, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.1.rda")
result2_0.1 <- DoSingleAnalysis(tree, data, 0.1, n.cores=2, rate.cat=2, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.1.rda")
result3_0.1 <- DoSingleAnalysis(tree, data, 0.1, n.cores=2, rate.cat=3, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.1.rda")
result4_0.1 <- DoSingleAnalysis(tree, data, 0.1, n.cores=2, rate.cat=4, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.1.rda")
result1_0.9 <- DoSingleAnalysis(tree, data, 0.9, n.cores=2, rate.cat=1, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.9.rda")
result2_0.9 <- DoSingleAnalysis(tree, data, 0.9, n.cores=2, rate.cat=2, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.9.rda")
result3_0.9 <- DoSingleAnalysis(tree, data, 0.9, n.cores=2, rate.cat=3, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.9.rda")
result4_0.9 <- DoSingleAnalysis(tree, data, 0.9, n.cores=2, rate.cat=4, nstarts=2, node.states="none")
save(list=ls(), file="ResultThreshold0.9.rda")
